server:
  port: 8083

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.30:8848
    config:
      uri: http://localhost:8888
      name: gateway-service
      profile: dev
      label: main

#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      default-filters:
#        - StripPrefix=1
